[package]
name = "kali_lir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kali_common = { workspace = true }
kali_error = { workspace = true }
kali_hir = { workspace = true }
kali_mir = { workspace = true }

[dev-dependencies]
kali_hir = { workspace = true }
kali_lexer = { workspace = true }
kali_parser = { workspace = true }
