//! The gate that makes §0.2 a reading of the oracle rather than a claim about
//! it.
//!
//! `kali-silent-miscompile-register.md` §0.2 says of its own rows: *"A row is
//! not prose a reader must re-derive: it is the verdict a live case asserts,
//! and a change of class is a red test."* Until this file existed the second
//! half was true and the first was not. Nothing read the oracle case files and
//! compared them to the table, so the table was regenerated by hand — and a
//! defect fixed, a case's `verdict` moved from `silent` to `fixed`, and the
//! case run green would have left §0.2 saying SILENT with nothing red
//! anywhere. That is the exact staleness this branch exists to end, and §0.2's
//! own prior row was stale for weeks in precisely this way.
//!
//! What is compared is the **set of classes per entry**, in both directions:
//! every entry §0.2 has a row for, every entry a case names, and for each the
//! set of lane classes. Sets, not multisets and not order: §0.2 records one
//! class per *lane* while the cases record one per *case*, and an entry's
//! lanes are measured by two cases each (module scope and in-function), so the
//! multiplicities legitimately differ. What may not differ is which classes an
//! entry carries.
//!
//! This lives under `ranking` because §0.2's parser does, and reading the table
//! with a second parser would let the two readings drift apart while both
//! stayed green.

use super::*;

use std::collections::{BTreeMap, BTreeSet};

/// The sentinel `register_entry` of a case that measures the classifier rather
/// than any entry. §0.2's own "how to read a row" paragraph names all four and
/// tells a reader to expect them to be unattributable; attributing them would
/// invent classes for an entry that never claimed them.
const GROUND_TRUTH: &str = "GROUND-TRUTH";

#[derive(serde::Deserialize)]
struct CaseFile {
    #[serde(default)]
    case: Vec<Case>,
}

#[derive(serde::Deserialize)]
struct Case {
    name: String,
    #[serde(default)]
    kind: String,
    #[serde(default)]
    register_entry: Option<String>,
    #[serde(default)]
    verdict: Option<String>,
}

fn oracle_dir() -> PathBuf {
    repo_root().join("crates/kali_cli/tests/cases/oracle")
}

/// Every case file in the oracle directory, sorted so a failure message names
/// the same file on every run.
fn oracle_case_files() -> Vec<PathBuf> {
    let dir = oracle_dir();
    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|error| panic!("{} is readable: {error}", dir.display()))
        .map(|entry| entry.expect("a directory entry is readable").path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "toml")
        })
        .collect();
    files.sort();
    assert!(
        !files.is_empty(),
        "no oracle case files found under {} -- every gate here would pass having read nothing",
        dir.display()
    );
    files
}

/// The `(register_entry, VERDICT)` pair of every `kind = "oracle"` case in one
/// case file, `GROUND-TRUTH` cases included. Both fields are required of an
/// oracle case by the runner's own model, so a missing one is a defect in the
/// case file rather than something to skip.
fn oracle_cases(text: &str, source: &str) -> Vec<(String, String)> {
    let parsed: CaseFile =
        toml::from_str(text).unwrap_or_else(|error| panic!("{source} parses as TOML: {error}"));
    parsed
        .case
        .into_iter()
        .filter(|case| case.kind == "oracle")
        .map(|case| {
            let name = &case.name;
            let entry = case
                .register_entry
                .clone()
                .unwrap_or_else(|| panic!("oracle case `{name}` in {source} names no entry"));
            let verdict = case
                .verdict
                .clone()
                .unwrap_or_else(|| panic!("oracle case `{name}` in {source} names no verdict"));
            (entry, verdict.to_uppercase())
        })
        .collect()
}

/// The classes the cases assert, grouped by entry, with the instrument-only
/// cases dropped.
fn group(cases: &[(String, String)]) -> BTreeMap<String, BTreeSet<String>> {
    let mut by_entry: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (entry, verdict) in cases {
        if entry == GROUND_TRUTH {
            continue;
        }
        by_entry
            .entry(entry.clone())
            .or_default()
            .insert(verdict.clone());
    }
    by_entry
}

/// Every oracle case in the directory, as `(entry, VERDICT)`.
fn all_oracle_cases() -> Vec<(String, String)> {
    let mut all = Vec::new();
    for path in oracle_case_files() {
        let text = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{} is readable: {error}", path.display()));
        all.extend(oracle_cases(&text, &path.display().to_string()));
    }
    all
}

#[test]
fn every_zero_two_row_is_the_class_set_its_live_cases_assert() {
    let register = fs::read_to_string(
        repo_root().join("docs/superpowers/followups/kali-silent-miscompile-register.md"),
    )
    .expect("the register is readable");
    let table = classes_by_entry(&register);
    let cases = group(&all_oracle_cases());

    assert!(
        !table.is_empty(),
        "§0.2 parsed to no rows -- this gate would pass having read nothing"
    );
    assert!(
        !cases.is_empty(),
        "no attributable oracle case parsed -- this gate would pass having read nothing"
    );

    let in_table: BTreeSet<&String> = table.keys().collect();
    let in_cases: BTreeSet<&String> = cases.keys().collect();
    assert_eq!(
        in_cases,
        in_table,
        "§0.2 and the oracle cases disagree about WHICH entries are measured. \
         Only in the cases: {:?}. Only in §0.2: {:?}. A row with no case is prose again; \
         a case with no row is a measurement nobody publishes.",
        in_cases.difference(&in_table).collect::<Vec<_>>(),
        in_table.difference(&in_cases).collect::<Vec<_>>(),
    );

    let mut divergences: Vec<String> = Vec::new();
    for (id, asserted) in &cases {
        let recorded = &table[id];
        if asserted != recorded {
            divergences.push(format!(
                "{id}: the cases assert {{{}}}, §0.2 records {{{}}}",
                asserted.iter().cloned().collect::<Vec<_>>().join(", "),
                recorded.iter().cloned().collect::<Vec<_>>().join(", "),
            ));
        }
    }
    assert!(
        divergences.is_empty(),
        "§0.2's status column no longer says what the oracle cases measure:\n  {}\n\
         §0.2 is regenerated FROM these cases, so the cases are the source: re-derive the \
         row rather than editing the case to match the row.",
        divergences.join("\n  ")
    );
}

/// The four instrument-only cases must stay unattributed, and must stay four.
/// If one of them ever acquired a real `register_entry`, the test above would
/// fold an instrument measurement into an entry's class set and could still be
/// green; §0.2's own paragraph commits to exactly four, out of exactly 149.
#[test]
fn exactly_four_oracle_cases_are_unattributed_and_all_of_them_are_ground_truth() {
    let cases = all_oracle_cases();
    let ground_truth = cases
        .iter()
        .filter(|(entry, _)| entry == GROUND_TRUTH)
        .count();
    assert_eq!(
        ground_truth, 4,
        "§0.2 records that exactly four oracle cases carry `register_entry = \"GROUND-TRUTH\"` \
         and are attributable to no row; a reader auditing the mapping is told to treat any \
         other unattributed case as a defect"
    );
    assert_eq!(
        cases.len(),
        149,
        "§0.2 states that 149 oracle cases exist and that 145 of them back its 41 rows; a \
         changed total needs that sentence regenerated with it"
    );
}

/// The gate is only worth having if it can fail. A moved verdict in one case
/// file must change the class set the comparison sees.
#[test]
fn a_moved_case_verdict_would_be_caught() {
    let path = oracle_dir().join("tier2.toml");
    let text = fs::read_to_string(&path).expect("tier2.toml is readable");
    // `timeout`, not `fixed`: several entries already carry a FIXED lane
    // beside a SILENT one, so flipping to a class the file already holds can
    // leave every class SET unchanged and prove nothing. TIMEOUT is asserted
    // by no case in this file, so the move is visible wherever it lands.
    let tampered = text.replace("verdict = \"silent\"", "verdict = \"timeout\"");
    assert_ne!(tampered, text, "the tamper probe changed nothing");

    assert_ne!(
        group(&oracle_cases(&text, "tier2.toml")),
        group(&oracle_cases(&tampered, "tier2.toml (tampered)")),
        "flipping a case's verdict did not change the class sets -- the comparison above \
         proves nothing as written"
    );
}
