//! C header text generation: the `Export` descriptor and the deterministic
//! header/identifier emitters.

/// Description of an exported entrypoint in the generated C header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Export {
    /// Exported symbol name.
    pub name: String,
    /// Number of C arguments emitted for the prototype.
    pub arity: usize,
}

impl Export {
    /// Create a new export description.
    pub fn new(name: impl Into<String>, arity: usize) -> Self {
        Self {
            name: name.into(),
            arity,
        }
    }
}

/// Infer the prototype arity from a Kali export signature string.
pub fn arity_from_signature(signature: &str) -> usize {
    let Some((params, _)) = signature.split_once(") =>") else {
        return 0;
    };
    let params = params.trim_start_matches('(').trim_end();
    if params.is_empty() {
        0
    } else {
        params.split(',').count()
    }
}

/// Generate a deterministic C header for the provided export surface.
pub fn generate_header(module_name: &str, exports: &[Export]) -> String {
    let mut header = String::new();
    header.push_str("#ifndef KALI_CAPI_GENERATED_H\n");
    header.push_str("#define KALI_CAPI_GENERATED_H\n\n");
    header.push_str("#include <stdint.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    header.push_str(&format!("/* Generated by Kali for {}. */\n", module_name));

    for export in exports {
        let name = sanitize_identifier(&export.name);
        header.push_str("extern int32_t ");
        header.push_str(&name);
        header.push('(');
        if export.arity == 0 {
            header.push_str("void");
        } else {
            for index in 0..export.arity {
                if index > 0 {
                    header.push_str(", ");
                }
                header.push_str(&format!("int32_t arg{index}"));
            }
        }
        header.push_str(");\n");
    }

    if exports.is_empty() {
        header.push_str("/* No exported symbols were discovered. */\n");
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str("#endif\n");
    header
}

/// Convert a symbol into a stable C identifier.
pub fn sanitize_identifier(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        let keep = ch.is_ascii_alphanumeric() || ch == '_';
        if index == 0 && ch.is_ascii_digit() {
            out.push('_');
            out.push(ch);
        } else if keep {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() {
        "_".to_string()
    } else {
        out
    }
}

#[cfg(test)]
#[path = "header_tests.rs"]
mod header_tests;
