//! C ABI bindings for Kali.
//!
//! This crate owns the deterministic C-header and metadata helpers used by the
//! public embedding projection.

use serde_json::{json, Value};

/// Current host ABI version expected by generated embedding metadata.
pub const HOST_ABI_VERSION: u32 = 2;

/// Description of an exported entrypoint in the generated C header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Export {
    /// Exported symbol name.
    pub name: String,
    /// Number of C arguments emitted for the prototype.
    pub arity: usize,
}

impl Export {
    /// Create a new export description.
    pub fn new(name: impl Into<String>, arity: usize) -> Self {
        Self {
            name: name.into(),
            arity,
        }
    }
}

/// Infer the prototype arity from a Kali export signature string.
pub fn arity_from_signature(signature: &str) -> usize {
    let Some((params, _)) = signature.split_once(") =>") else {
        return 0;
    };
    let params = params.trim_start_matches('(').trim_end();
    if params.is_empty() {
        0
    } else {
        params.split(',').count()
    }
}

/// Generate the canonical C ABI metadata payload.
pub fn generate_metadata(
    wasm_module_path: impl AsRef<str>,
    wit_path: impl AsRef<str>,
    exports_header_path: impl AsRef<str>,
) -> Value {
    json!({
        "schemaVersion": 1,
        "kind": "cabi-metadata",
        "hostAbiVersion": HOST_ABI_VERSION,
        "minHostAbiVersion": HOST_ABI_VERSION,
        "artifacts": {
            "wasmModule": wasm_module_path.as_ref(),
            "wit": wit_path.as_ref(),
            "exportsHeader": exports_header_path.as_ref(),
        },
    })
}

/// Generate a deterministic C header for the provided export surface.
pub fn generate_header(module_name: &str, exports: &[Export]) -> String {
    let mut header = String::new();
    header.push_str("#ifndef KALI_CAPI_GENERATED_H\n");
    header.push_str("#define KALI_CAPI_GENERATED_H\n\n");
    header.push_str("#include <stdint.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    header.push_str(&format!(
        "/* Generated by Kali for {}. */\n",
        module_name
    ));

    for export in exports {
        let name = sanitize_identifier(&export.name);
        header.push_str("extern int32_t ");
        header.push_str(&name);
        header.push('(');
        if export.arity == 0 {
            header.push_str("void");
        } else {
            for index in 0..export.arity {
                if index > 0 {
                    header.push_str(", ");
                }
                header.push_str(&format!("int32_t arg{index}"));
            }
        }
        header.push_str(");\n");
    }

    if exports.is_empty() {
        header.push_str("/* No exported symbols were discovered. */\n");
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str("#endif\n");
    header
}

/// Convert a symbol into a stable C identifier.
pub fn sanitize_identifier(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        let keep = ch.is_ascii_alphanumeric() || ch == '_';
        if index == 0 && ch.is_ascii_digit() {
            out.push('_');
            out.push(ch);
        } else if keep {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() {
        "_".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn metadata_generation_includes_expected_artifacts() {
        let metadata = generate_metadata("lib.capi.wasm", "lib.wit", "lib.h");
        assert_eq!(metadata["schemaVersion"], 1);
        assert_eq!(metadata["kind"], "cabi-metadata");
        assert_eq!(metadata["hostAbiVersion"], HOST_ABI_VERSION);
        assert_eq!(metadata["artifacts"]["wasmModule"], "lib.capi.wasm");
        assert_eq!(metadata["artifacts"]["wit"], "lib.wit");
        assert_eq!(metadata["artifacts"]["exportsHeader"], "lib.h");
    }

    #[test]
    fn header_generation_produces_c_compatible_prototypes() {
        let header = generate_header(
            "lib",
            &[
                Export::new("add", 2),
                Export::new("1bad-name", 0),
            ],
        );

        assert!(header.contains("#include <stdint.h>"));
        assert!(header.contains("extern int32_t add(int32_t arg0, int32_t arg1);"));
        assert!(header.contains("extern int32_t _1bad_name(void);"));
    }

    #[test]
    fn identifier_sanitization_is_deterministic() {
        assert_eq!(sanitize_identifier("foo-bar"), "foo_bar");
        assert_eq!(sanitize_identifier("1foo"), "_1foo");
        assert_eq!(sanitize_identifier(""), "_");
    }
}
