//! C ABI bindings for Kali.
//!
//! This crate owns the deterministic C-header and metadata helpers used by the
//! public embedding projection.

use serde_json::{json, Value};

/// Current host ABI version expected by generated embedding metadata.
pub const HOST_ABI_VERSION: u32 = 2;

/// Description of an exported entrypoint in the generated C header.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Export {
    /// Exported symbol name.
    pub name: String,
    /// Number of C arguments emitted for the prototype.
    pub arity: usize,
}

impl Export {
    /// Create a new export description.
    pub fn new(name: impl Into<String>, arity: usize) -> Self {
        Self {
            name: name.into(),
            arity,
        }
    }
}

/// Infer the prototype arity from a Kali export signature string.
pub fn arity_from_signature(signature: &str) -> usize {
    let Some((params, _)) = signature.split_once(") =>") else {
        return 0;
    };
    let params = params.trim_start_matches('(').trim_end();
    if params.is_empty() {
        0
    } else {
        params.split(',').count()
    }
}

/// Generate the canonical C ABI metadata payload.
pub fn generate_metadata(
    wasm_module_path: impl AsRef<str>,
    wit_path: impl AsRef<str>,
    exports_header_path: impl AsRef<str>,
) -> Value {
    json!({
        "schemaVersion": 1,
        "kind": "cabi-metadata",
        "hostAbiVersion": HOST_ABI_VERSION,
        "minHostAbiVersion": HOST_ABI_VERSION,
        "artifacts": {
            "wasmModule": wasm_module_path.as_ref(),
            "wit": wit_path.as_ref(),
            "exportsHeader": exports_header_path.as_ref(),
        },
    })
}

/// Generate a deterministic packaging manifest for higher-level language bindings.
pub fn generate_binding_package_manifest(
    module_name: impl AsRef<str>,
    library_path: impl AsRef<str>,
    metadata_path: impl AsRef<str>,
    exports_header_path: impl AsRef<str>,
    glue_paths: &[String],
) -> Value {
    let mut glue_paths: Vec<_> = glue_paths.iter().map(String::as_str).collect();
    glue_paths.sort();
    glue_paths.dedup();

    json!({
        "schemaVersion": 1,
        "kind": "binding-package",
        "moduleName": module_name.as_ref(),
        "hostAbiVersion": HOST_ABI_VERSION,
        "minHostAbiVersion": HOST_ABI_VERSION,
        "artifacts": {
            "library": library_path.as_ref(),
            "metadata": metadata_path.as_ref(),
            "exportsHeader": exports_header_path.as_ref(),
            "glue": glue_paths,
        },
    })
}

/// Generate a deterministic C header for the provided export surface.
pub fn generate_header(module_name: &str, exports: &[Export]) -> String {
    let mut header = String::new();
    header.push_str("#ifndef KALI_CAPI_GENERATED_H\n");
    header.push_str("#define KALI_CAPI_GENERATED_H\n\n");
    header.push_str("#include <stdint.h>\n\n");
    header.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");
    header.push_str(&format!("/* Generated by Kali for {}. */\n", module_name));

    for export in exports {
        let name = sanitize_identifier(&export.name);
        header.push_str("extern int32_t ");
        header.push_str(&name);
        header.push('(');
        if export.arity == 0 {
            header.push_str("void");
        } else {
            for index in 0..export.arity {
                if index > 0 {
                    header.push_str(", ");
                }
                header.push_str(&format!("int32_t arg{index}"));
            }
        }
        header.push_str(");\n");
    }

    if exports.is_empty() {
        header.push_str("/* No exported symbols were discovered. */\n");
    }

    header.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    header.push_str("#endif\n");
    header
}

/// Convert a symbol into a stable C identifier.
pub fn sanitize_identifier(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        let keep = ch.is_ascii_alphanumeric() || ch == '_';
        if index == 0 && ch.is_ascii_digit() {
            out.push('_');
            out.push(ch);
        } else if keep {
            out.push(ch);
        } else {
            out.push('_');
        }
    }

    if out.is_empty() {
        "_".to_string()
    } else {
        out
    }
}

#[cfg(test)]
#[path = "tests.rs"]
mod tests;
