[package]
name = "kali_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
[[bin]]
name = "kali"
path = "src/bin/kali.rs"

[dependencies]
clap = { workspace = true }
kali_common = { workspace = true }
kali_error = { workspace = true }
kali_lexer = { workspace = true }
kali_parser = { workspace = true }
kali_hir = { workspace = true }
kali_mir = { workspace = true }
kali_lir = { workspace = true }
kali_codegen = { workspace = true }
kali_runtime = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
wasmparser = { workspace = true }
