#!/usr/bin/env python3
"""Assert every fixture program in a .rs survives verbatim into its .toml.

Why this exists (a real bug from Task 18 batch 4, not a hypothetical): case
files are generated by pulling string literals out of the .rs by position. A
position that drifts -- because a `//!` retention header was inserted or
deleted, shifting every line below it -- silently extracts the WRONG literal.
The generated TOML still parses, `cargo test` still runs, and the fixture is
some unrelated `.expect()` message. Observed output was literally:

    [source]
    "app.${ext}"  = "KALI_BROWSER_BUNDLE_HARNESS_COMMAND"
    "main.${ext}" = "run browser bundle harness"

Nothing else in the verification stack fails loudly on that. `cargo test` fails
with a JS compile error that reads like a product bug, not a migration bug;
`audit-case-migration.py` never reads `[source]` at all (by design -- program
text is not a claim); `fidelity.py` does report the real fixture as `missing`,
but buries it among ~30 expected panic-message entries.

So: this checks the one property that matters. Every "fixture-shaped" string
literal in the .rs -- the return value of a `fn *_source() -> &'static str`,
and any literal that looks like a program body -- must appear verbatim as some
`[source]` value or step `body` in the .toml. Reports each unmatched one.

Exits 1 if any fixture is unmatched, 2 if it found no fixtures to check at all
(a vacuous green, the dangerous direction -- same floor `comment_coverage.py`
grew in batch 3).

Usage: check_fixtures.py SOURCE.rs TARGET.toml [TARGET2.toml ...]
"""

import os
import re
import sys
import tomllib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from case_emit import fixture_in_fn  # noqa: E402
from lexer import find_string_literals  # noqa: E402
from submodules import read_with_submodules  # noqa: E402

SOURCE_FN = re.compile(r"\bfn\s+([a-z0-9_]*source[a-z0-9_]*)\s*\(\s*\)\s*->\s*&'static\s+str")
# A literal is "program-shaped" if it spans lines or reads like JS/TS.
PROGRAM_HINT = re.compile(r"console\.log|Kali\.test|await import|function\s|const\s|export\s")


def _format_segments(template):
    """The literal (non-placeholder) segments of a `format!` template, with
    `{{`/`}}` un-doubled -- i.e. the parts that must survive verbatim into the
    resolved string."""
    tmp = template.replace("{{", "\x00").replace("}}", "\x01")
    parts = re.split(r"\{[^{}]*\}", tmp)
    return [p.replace("\x00", "{").replace("\x01", "}") for p in parts]


def toml_program_texts(path):
    doc = tomllib.load(open(path, "rb"))
    out = []
    for v in (doc.get("source") or {}).values():
        if isinstance(v, str):
            out.append(v)
    for case in doc.get("case") or []:
        steps = case.get("step") or [case]
        for st in steps:
            if isinstance(st, dict) and isinstance(st.get("body"), str):
                out.append(st["body"])
    return out


def main(argv):
    if len(argv) < 2:
        raise SystemExit(__doc__)
    rs_path, toml_paths = argv[0], argv[1:]
    # U10: a submodule carrier may declare its fixtures in the carrier, in a
    # submodule, or in both. Reading only the carrier would report "VACUOUS: no
    # fixture-shaped literals" -- exit 2, not a green -- for a carrier that
    # holds only `mod` declarations, but would report a FALSE GREEN for one that
    # holds some fixtures and leaves others in a submodule. Same resolution
    # `audit-case-migration.py` does for itself.
    text = read_with_submodules(rs_path)

    wanted = {}
    for m in SOURCE_FN.finditer(text):
        name = m.group(1)
        wanted[name] = fixture_in_fn(text, name)
    for lit in find_string_literals(text):
        v = lit["value"]
        if PROGRAM_HINT.search(v) and v not in wanted.values():
            wanted.setdefault(f"<inline literal at offset {lit['start']}>", v)

    if not wanted:
        print(f"VACUOUS: no fixture-shaped literals found in {rs_path}")
        return 2

    haystacks = []
    for p in toml_paths:
        haystacks.extend(toml_program_texts(p))

    missing = []
    for name, body in wanted.items():
        # A fixture may be embedded with ${ext} substituted into its filename,
        # never into its body, so an exact containment check is right here.
        if any(body == h or body in h for h in haystacks):
            continue
        # ...unless the fixture is built by `format!`. Then the .rs holds the
        # UNRESOLVED template (`{}` placeholders, `{{`/`}}` escapes) while the
        # case file correctly holds the RESOLVED text -- rule 8 requires the
        # resolved string be captured by executing the real code, so an exact
        # match is the wrong test and would fail every correctly-migrated
        # format!-built fixture. Compare the template's LITERAL segments
        # instead: each must still appear verbatim. That keeps the gate honest
        # about wrong-literal extraction (the bug this file exists for) while
        # tolerating substitution.
        segs = [s for s in _format_segments(body) if len(s) >= 12]
        if segs and all(any(s in h for h in haystacks) for s in segs):
            print(f"  format!-built (segments matched): {name}")
            continue
        missing.append((name, body))

    print(f"{len(wanted)} fixture(s) in {os.path.basename(rs_path)}; "
          f"{len(haystacks)} program text(s) in {len(toml_paths)} case file(s)")
    for name, body in missing:
        print(f"  UNMATCHED: {name}\n    {body[:120]!r}")
    if missing:
        print(f"FIXTURE CHECK FAILED — {len(missing)} fixture(s) not present verbatim")
        return 1
    print("FIXTURE CHECK OK — every fixture program appears verbatim")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
