"""Rule-8 / rule-9 captured fixture texts for Task 19 batch 5.

EVERY CONSTANT HERE IS THE BYTE-EXACT OUTPUT OF EXECUTING THE REAL CODE. Rule 8
forbids hand-simulating a `format!`; rule 9 extends the same discipline to a
fixture built one level removed inside a library crate (`kali_common::`). The
fixtures in this batch that exist as plain string literals are NOT here --
`gen_task19_batch5.py` pulls those straight out of the `.rs` through
`lexer.find_string_literals`, which is this project's copy-never-retype
mechanism. Only a fixture that exists as a literal NOWHERE needs a capture.

HOW THEY WERE CAPTURED, so they can be re-derived -- `t19b5_capture_run.py`,
committed beside this file, is the script and it uses two mechanisms:

  A. `RUNTIME_FORIN` -- the eleven `runtime_forin` `#[test]`s whose fixture is
     built by the `format!` inside `forin_ternary_case` / `forin_leak_case`.
     Those helpers hand the string straight to `run_source`, so there is no
     builder to call; but `run_source` writes the program to
     `std::env::temp_dir()/kali-forin-<pid>-<counter>-<len>/main.ts` and never
     cleans up. Each `#[test]` was run ALONE with its own `TMPDIR`, and the one
     file left behind is the real `format!`'s output, obtained by executing it.

  B. `SPREAD` -- `for_of_array_iteration_spread`'s five builder outputs, taken
     by `include!`ing the shipped source into a module and calling the builders
     from inside it (they are private, so a sibling module cannot name them).
     `include!` rather than a copy, so the executed `format!` and the executed
     `kali_common::` call are literally the ones in the source under migration.

WHAT KEEPS THEM FROM GOING STALE. `gen_task19_batch5.check_captured` re-checks
every capture against its own `.rs` before it is emitted: the fn must still
exist, and it must still build its value the way the capture was taken for. A
capture taken before a source edit therefore fails the generator instead of
shipping a program that is no longer the program under test. The eleven
`RUNTIME_FORIN` entries carry a second, independent check -- the generator
recomputes the `format!` substitution structurally and requires it to agree
with the executed bytes. The capture is what SHIPS; the recomputation is a
cross-check that would catch either one being wrong.
"""

# key: the `#[test]` fn whose single invocation wrote this program.
RUNTIME_FORIN = {
    'for_in_key_closure_capture_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { for (var c in tab) { let g = () => c; return g(); } return 0; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_compound_assign_target_value_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var x = 0; for (var c in tab) { return (x += c); } return 0; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_nested_ternary_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; return (1 < 2 ? (1 < 2 ? c : d) : d); } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_ternary_arm_at_array_element_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; let a = [1 < 2 ? c : d]; return a[0]; } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_ternary_arm_at_console_arg_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; console.log(1 < 2 ? c : d); return "?"; } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_ternary_arm_at_general_call_arg_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; return id(1 < 2 ? c : d); } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_ternary_arm_at_object_property_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; let o = { k: 1 < 2 ? c : d }; return o.k; } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_in_ternary_arm_at_return_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var d; for (var c in tab) { d = c; return (1 < 2 ? c : d); } return "?"; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_numeric_accumulate_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { var out = 0; for (var c in tab) { out += c; } return out; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_optional_chain_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { for (var c in tab) { return c?.length; } return 0; }\n'
            'console.log(f(t));\n'
        ),
    'for_in_key_unary_negate_is_fail_closed':
        (
            'const t = { a: 0.5, c: 0.5 };\n'
            'function id(x) { return x; }\n'
            'function f(tab) { for (var c in tab) { return -c; } return 0; }\n'
            'console.log(f(t));\n'
        ),
}

# key: the builder call, spelled as the evaluator renders it.
SPREAD = {
    'array_from_iteration_body()':
        (
            'const values = [1, 2];\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
        ),
    'browser_harness_array_from_source("run")':
        (
            'const values = [1, 2];\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
        ),
    'browser_harness_array_from_source("test")':
        (
            "Kali.test('browser Array.from wrappers', () => {\n"
            '  async function browserArrayFromWrappers() {\n'
            'const values = [1, 2];\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array.from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"].from(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"]["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis["Array"][\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array'].from(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis['Array']['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis[\'Array\']["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of globalThis.Array["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of globalThis.Array['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array.from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"].from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"])[\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"]["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array'].from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']).from)(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\'])["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"]))[\'from\'](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis['Array']['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis["Array"][\'from\'])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'])['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis[\'Array\']["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis[\'Array\']["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze(globalThis.Array['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze(globalThis.Array["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array).from)(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array)["from"])(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array))["from"](values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array))['from'](values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis.Array)['from'])(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((Array.from, Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis.Array.from, globalThis.Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((globalThis["Array"].from, globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((globalThis['Array'].from, globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || Array.from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"].from))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"]["from"]))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array']['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis['Array'].from))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((null ?? globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((true && globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            'for await (const value of Object.freeze((false || globalThis["Array"][\'from\']))(values)) {\n'
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((null ?? globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((true && globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            "for await (const value of Object.freeze((false || globalThis.Array['from']))(values)) {\n"
            '  console.log(value);\n'
            '}\n'
            '  }\n'
            '  return browserArrayFromWrappers();\n'
            '});\n'
        ),
    'browser_harness_array_from_set_map_break_continue_source("run")':
        (
            'async function browserArrayFromSetMapBreakContinue() {\n'
            '  const setValues = [0, 1, 1];\n'
            '  const setItems = [];\n'
            '  for (const value of Array.from(new Set(setValues))) {\n'
            '    if (!value) {\n'
            '      continue;\n'
            '    }\n'
            '    setItems.push(value);\n'
            '    break;\n'
            '  }\n'
            '  if (setItems.length !== 1 || setItems[0] !== 1) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) break/continue semantics');\n"
            '  }\n'
            '\n'
            '  let setReturnFinally = false;\n'
            '  async function setReturnProbe() {\n'
            '    try {\n'
            '      for (const value of Array.from(new Set(setValues))) {\n'
            '        return value;\n'
            '      }\n'
            "      throw new Error('unexpected empty Array.from(new Set(...)) iteration');\n"
            '    } finally {\n'
            '      setReturnFinally = true;\n'
            '    }\n'
            '  }\n'
            '  const setReturnValue = await setReturnProbe();\n'
            '  if (setReturnValue !== 1 || !setReturnFinally) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) return/finally semantics');\n"
            '  }\n'
            '\n'
            '  let setThrowFinally = false;\n'
            '  async function setThrowProbe() {\n'
            '    try {\n'
            '      for (const value of Array.from(new Set(setValues))) {\n'
            '        if (value === 1) {\n'
            "          throw new Error('boom');\n"
            '        }\n'
            '      }\n'
            "      throw new Error('unexpected empty Array.from(new Set(...)) iteration');\n"
            '    } finally {\n'
            '      setThrowFinally = true;\n'
            '    }\n'
            '  }\n'
            '  let setThrew = false;\n'
            '  try {\n'
            '    await setThrowProbe();\n'
            '  } catch {\n'
            '    setThrew = true;\n'
            '  }\n'
            '  if (!setThrew || !setThrowFinally) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) throw/finally semantics');\n"
            '  }\n'
            '\n'
            '  const mapItems = [];\n'
            '  for await (const entry of Array.from(new Map([[0, 1], [1, 3], [4, 5]]))) {\n'
            '    if (!entry[0]) {\n'
            '      continue;\n'
            '    }\n'
            '    mapItems.push(entry[0]);\n'
            '    mapItems.push(entry[1]);\n'
            '    break;\n'
            '  }\n'
            '  if (mapItems.length !== 2 || mapItems[0] !== 1 || mapItems[1] !== 3) {\n'
            "    throw new Error('unexpected Array.from(new Map(...)) break/continue semantics');\n"
            '  }\n'
            '\n'
            '  console.log(1);\n'
            '  console.log(2);\n'
            "  console.log('array.from set/map break/continue ok');\n"
            '}\n'
            '\n'
            'browserArrayFromSetMapBreakContinue();\n'
        ),
    'browser_harness_array_from_set_map_break_continue_source("test")':
        (
            "Kali.test('browser Array.from set/map break/continue', () => {\n"
            '  async function browserArrayFromSetMapBreakContinue() {\n'
            '  const setValues = [0, 1, 1];\n'
            '  const setItems = [];\n'
            '  for (const value of Array.from(new Set(setValues))) {\n'
            '    if (!value) {\n'
            '      continue;\n'
            '    }\n'
            '    setItems.push(value);\n'
            '    break;\n'
            '  }\n'
            '  if (setItems.length !== 1 || setItems[0] !== 1) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) break/continue semantics');\n"
            '  }\n'
            '\n'
            '  let setReturnFinally = false;\n'
            '  async function setReturnProbe() {\n'
            '    try {\n'
            '      for (const value of Array.from(new Set(setValues))) {\n'
            '        return value;\n'
            '      }\n'
            "      throw new Error('unexpected empty Array.from(new Set(...)) iteration');\n"
            '    } finally {\n'
            '      setReturnFinally = true;\n'
            '    }\n'
            '  }\n'
            '  const setReturnValue = await setReturnProbe();\n'
            '  if (setReturnValue !== 1 || !setReturnFinally) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) return/finally semantics');\n"
            '  }\n'
            '\n'
            '  let setThrowFinally = false;\n'
            '  async function setThrowProbe() {\n'
            '    try {\n'
            '      for (const value of Array.from(new Set(setValues))) {\n'
            '        if (value === 1) {\n'
            "          throw new Error('boom');\n"
            '        }\n'
            '      }\n'
            "      throw new Error('unexpected empty Array.from(new Set(...)) iteration');\n"
            '    } finally {\n'
            '      setThrowFinally = true;\n'
            '    }\n'
            '  }\n'
            '  let setThrew = false;\n'
            '  try {\n'
            '    await setThrowProbe();\n'
            '  } catch {\n'
            '    setThrew = true;\n'
            '  }\n'
            '  if (!setThrew || !setThrowFinally) {\n'
            "    throw new Error('unexpected Array.from(new Set(...)) throw/finally semantics');\n"
            '  }\n'
            '\n'
            '  const mapItems = [];\n'
            '  for await (const entry of Array.from(new Map([[0, 1], [1, 3], [4, 5]]))) {\n'
            '    if (!entry[0]) {\n'
            '      continue;\n'
            '    }\n'
            '    mapItems.push(entry[0]);\n'
            '    mapItems.push(entry[1]);\n'
            '    break;\n'
            '  }\n'
            '  if (mapItems.length !== 2 || mapItems[0] !== 1 || mapItems[1] !== 3) {\n'
            "    throw new Error('unexpected Array.from(new Map(...)) break/continue semantics');\n"
            '  }\n'
            '\n'
            '  console.log(1);\n'
            '  console.log(2);\n'
            "  console.log('array.from set/map break/continue ok');\n"
            '  }\n'
            '  return browserArrayFromSetMapBreakContinue();\n'
            '});\n'
        ),
}
