[package]
name = "kali_codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kali_common = { workspace = true }
kali_error = { workspace = true }
kali_lir = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
kali_common = { workspace = true }
kali_hir = { workspace = true }
kali_lexer = { workspace = true }
kali_mir = { workspace = true }
kali_parser = { workspace = true }
wasmprinter = "0.240"
