#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export CARGO_TERM_COLOR=${CARGO_TERM_COLOR:-always}

run_exact_test() {
  local test_name=$1
  cargo test -p kali_cli --test runtime_smoke "$test_name" -- --exact
}

run_exact_test build_artifacts_are_deterministic_across_repeated_invocations
run_exact_test build_with_profile_data_is_deterministic_across_repeated_invocations
run_exact_test effects_command_is_deterministic_across_repeated_json_envelope_invocations
run_exact_test effects_command_is_deterministic_across_repeated_pretty_json_envelope_invocations_under_quiet_inherited_browser_context
run_exact_test package_effects_command_is_deterministic_across_repeated_invocations
run_exact_test package_effects_command_is_deterministic_across_repeated_json_envelope_invocations
run_exact_test package_effects_command_is_deterministic_across_repeated_pretty_invocations_under_quiet
run_exact_test package_audit_command_is_deterministic_across_repeated_invocations
run_exact_test package_audit_command_is_deterministic_across_repeated_json_envelope_invocations_under_inherited_browser_context
run_exact_test package_audit_command_is_deterministic_in_human_output
run_exact_test package_audit_command_is_deterministic_across_repeated_pretty_json_envelope_invocations_under_quiet
run_exact_test test_reports_function_coverage_is_deterministic_across_repeated_runs
