//! Diagnostic types and collection.

use super::severity::Severity;
use std::fmt;
use kali_common::{Span, FileId};

#[cfg(feature = "serde")]
use serde::Deserialize;

#[cfg(feature = "serde")]
use serde::Serialize;

/// Represents a diagnostic message generated by the compiler.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Diagnostic {
    /// Severity level of this diagnostic.
    pub severity: Severity,
    /// Error code if applicable.
    pub code: Option<u32>,
    /// Human-readable message.
    pub message: String,
    /// Span where this diagnostic originates (if known).
    pub span: Option<Span>,
    /// Suggested fix text (optional).
    pub suggestion: Option<String>,
    /// Additional notes or context.
    pub notes: Vec<String>,
}

impl Diagnostic {
    /// Create a new error-level diagnostic.
    pub fn error(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Error,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
        }
    }

    /// Create a new warning-level diagnostic.
    pub fn warning(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Warning,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
        }
    }

    /// Create a new info-level diagnostic.
    pub fn info(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Info,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
        }
    }

    /// Create a new diagnostic with custom code.
    pub fn new(severity: Severity, code: u32, message: impl Into<String>) -> Self {
        Self {
            severity,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
        }
    }

    /// Create a diagnostic without an error code.
    pub fn generic(severity: Severity, message: impl Into<String>) -> Self {
        Self {
            severity,
            code: None,
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
        }
    }

    /// Set the span for this diagnostic.
    #[must_use]
    pub fn with_span(mut self, span: Span) -> Self {
        self.span = Some(span);
        self
    }

    /// Set a fix suggestion for this diagnostic.
    #[must_use]
    pub fn with_suggestion(mut self, suggestion: impl Into<String>) -> Self {
        self.suggestion = Some(suggestion.into());
        self
    }

    /// Add a note to this diagnostic.
    #[must_use]
    pub fn note(mut self, text: impl Into<String>) -> Self {
        self.notes.push(text.into());
        self
    }

    /// Check if this is an error.
    pub fn is_error(&self) -> bool {
        self.severity == Severity::Error
    }

    /// Check if this is a warning.
    pub fn is_warning(&self) -> bool {
        self.severity == Severity::Warning
    }

    /// Check if this is an info-level diagnostic.
    pub fn is_info(&self) -> bool {
        self.severity == Severity::Info
    }

    /// Format this diagnostic for terminal output.
    pub fn format_terminal(&self) -> String {
        let mut output = String::new();

        // Severity prefix
        let prefix = match self.severity {
            Severity::Error => "Error",
            Severity::Warning => "Warning",
            Severity::Info => "Info",
        };

        // Code and message
        output.push_str(prefix);
        if let Some(code) = self.code {
            output.push_str(&format!("[E{:04}]", code));
        }

        output.push_str(": ");
        output.push_str(&self.message);

        // Span information
        if let Some(span) = self.span {
            if let Some(span_info) = format_span(&span) {
                output.push_str(&format!("\n  at {}", span_info));
            }
        }

        // Suggestions
        if let Some(suggestion) = &self.suggestion {
            output.push_str(&format!("\n  help: {}", suggestion));
        }

        // Notes
        for note in &self.notes {
            output.push_str(&format!("\n  note: {}", note));
        }

        output
    }
}

impl fmt::Display for Diagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.format_terminal())
    }
}

/// Format a span for display.
fn format_span(span: &Span) -> Option<String> {
    Some(format!("file_{}:{}:{}", span.file_id.as_u32(), span.start, span.end))
}

/// Format a file reference for display.
fn format_file_ref(file_id: &FileId) -> String {
    format!("file_{}", file_id.as_u32())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_diagnostic_creation() {
        let diag = Diagnostic::new(
            Severity::Error,
            1000,
            "test error".to_string()
        );
        
        assert_eq!(diag.severity, Severity::Error);
        assert_eq!(diag.code, Some(1000));
    }
}
