//! Diagnostic types and collection.

use super::severity::Severity;
use kali_common::Span;
use std::fmt;
use std::sync::atomic::{AtomicBool, Ordering};

#[cfg(feature = "serde")]
use serde::Deserialize;

#[cfg(feature = "serde")]
use serde::Serialize;

static VERBOSE_DIAGNOSTICS: AtomicBool = AtomicBool::new(false);

/// Set whether terminal diagnostics should include verbose docs links.
pub fn set_verbose_diagnostics(enabled: bool) {
    VERBOSE_DIAGNOSTICS.store(enabled, Ordering::Relaxed);
}

fn verbose_diagnostics_enabled() -> bool {
    VERBOSE_DIAGNOSTICS.load(Ordering::Relaxed)
}

/// Represents a diagnostic message generated by the compiler.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Diagnostic {
    /// Severity level of this diagnostic.
    pub severity: Severity,
    /// Error code if applicable.
    pub code: Option<u32>,
    /// Human-readable message.
    pub message: String,
    /// Span where this diagnostic originates (if known).
    pub span: Option<Span>,
    /// Suggested fix text (optional).
    pub suggestion: Option<String>,
    /// Additional notes or context.
    pub notes: Vec<String>,
    /// Structured command/config context when the diagnostic depends on the effective invocation state.
    pub context: Option<Box<DiagnosticContext>>,
}

impl Diagnostic {
    /// Create a new error-level diagnostic.
    pub fn error(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Error,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
            context: None,
        }
    }

    /// Create a new warning-level diagnostic.
    pub fn warning(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Warning,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
            context: None,
        }
    }

    /// Create a new info-level diagnostic.
    pub fn info(code: u32, message: impl Into<String>) -> Self {
        Self {
            severity: Severity::Info,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
            context: None,
        }
    }

    /// Create a new diagnostic with custom code.
    pub fn new(severity: Severity, code: u32, message: impl Into<String>) -> Self {
        Self {
            severity,
            code: Some(code),
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
            context: None,
        }
    }

    /// Create a diagnostic without an error code.
    pub fn generic(severity: Severity, message: impl Into<String>) -> Self {
        Self {
            severity,
            code: None,
            message: message.into(),
            span: None,
            suggestion: None,
            notes: Vec::new(),
            context: None,
        }
    }

    /// Set the span for this diagnostic.
    #[must_use]
    pub fn with_span(mut self, span: Span) -> Self {
        self.span = Some(span);
        self
    }

    /// Set a fix suggestion for this diagnostic.
    #[must_use]
    pub fn with_suggestion(mut self, suggestion: impl Into<String>) -> Self {
        self.suggestion = Some(suggestion.into());
        self
    }

    /// Add a note to this diagnostic.
    #[must_use]
    pub fn note(mut self, text: impl Into<String>) -> Self {
        self.notes.push(text.into());
        self
    }

    /// Attach structured command/config context to this diagnostic.
    #[must_use]
    pub fn with_context(mut self, context: DiagnosticContext) -> Self {
        self.context = Some(Box::new(context));
        self
    }

    /// Check if this is an error.
    pub fn is_error(&self) -> bool {
        self.severity == Severity::Error
    }

    /// Check if this is a warning.
    pub fn is_warning(&self) -> bool {
        self.severity == Severity::Warning
    }

    /// Check if this is an info-level diagnostic.
    pub fn is_info(&self) -> bool {
        self.severity == Severity::Info
    }

    /// Format this diagnostic for terminal output.
    pub fn format_terminal(&self) -> String {
        self.format_terminal_with_verbose(verbose_diagnostics_enabled())
    }

    /// Format this diagnostic for terminal output with an explicit verbosity choice.
    pub fn format_terminal_with_verbose(&self, verbose: bool) -> String {
        let mut output = String::new();

        let severity = match self.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
            Severity::Info => "info",
        };

        output.push_str(severity);
        if let Some(code) = self.code {
            output.push_str(&format!("[E{:04}]", code));
        }

        output.push_str(": ");
        output.push_str(&self.message);

        if let Some(span) = self.span {
            if let Some(span_info) = format_span(&span) {
                output.push_str(&format!("\n  --> {}", span_info));
            }
        }

        if verbose {
            if let Some(code) = self.code {
                output.push_str(&format!(
                    "\n  = note: docs: https://kali-lang.org/errors/E{:04}",
                    code
                ));
            }
        }

        if let Some(suggestion) = &self.suggestion {
            output.push_str(&format!("\n  = help: {}", suggestion));
        }

        for note in &self.notes {
            output.push_str(&format!("\n  = note: {}", note));
        }

        output
    }
}

/// Structured command/config context for diagnostics.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct DiagnosticContext {
    /// Where the effective value came from.
    pub origin: DiagnosticContextOrigin,
    /// Canonical config path when a discovered/inherited config value caused the diagnostic.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub config_path: Option<String>,
    /// Canonical CLI flag spelling when an explicit flag caused the diagnostic.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub flag: Option<String>,
    /// User-requested value before normalization, if relevant.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub requested_value: Option<String>,
    /// Normalized value the command actually validated against.
    #[cfg_attr(feature = "serde", serde(skip_serializing_if = "Option::is_none"))]
    pub effective_value: Option<String>,
}

impl DiagnosticContext {
    /// Construct a context value with the given origin.
    pub fn new(origin: DiagnosticContextOrigin) -> Self {
        Self {
            origin,
            config_path: None,
            flag: None,
            requested_value: None,
            effective_value: None,
        }
    }

    /// Attach a config path to the context.
    #[must_use]
    pub fn with_config_path(mut self, config_path: impl Into<String>) -> Self {
        self.config_path = Some(config_path.into());
        self
    }

    /// Attach a CLI flag to the context.
    #[must_use]
    pub fn with_flag(mut self, flag: impl Into<String>) -> Self {
        self.flag = Some(flag.into());
        self
    }

    /// Attach the requested value to the context.
    #[must_use]
    pub fn with_requested_value(mut self, requested_value: impl Into<String>) -> Self {
        self.requested_value = Some(requested_value.into());
        self
    }

    /// Attach the effective value to the context.
    #[must_use]
    pub fn with_effective_value(mut self, effective_value: impl Into<String>) -> Self {
        self.effective_value = Some(effective_value.into());
        self
    }
}

/// Canonical source of an effective diagnostic context.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "lowercase"))]
pub enum DiagnosticContextOrigin {
    Cli,
    Config,
    Default,
    Source,
}

impl fmt::Display for Diagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.format_terminal())
    }
}

/// Format a span for display.
fn format_span(span: &Span) -> Option<String> {
    Some(format!(
        "file_{}:{}..{}",
        span.file_id.as_u32(),
        span.start,
        span.end
    ))
}

#[cfg(test)]
#[path = "diagnostic_tests.rs"]
mod tests;
