[package]
name = "kali_optimize"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kali_common = { workspace = true }
kali_error = { workspace = true }
kali_lir = { workspace = true }
kali_mir = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
